/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SimpleBankingSystem;

import java.awt.Color;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jowie james
 */
public class AdminDashboard extends javax.swing.JFrame {

    String userAcc = "C:\\Users\\ADMIN\\Documents\\NetBeansProjects\\LoginApp\\LoginApp\\UsersAccount.txt";
    String historyData = "C:\\Users\\ADMIN\\Documents\\NetBeansProjects\\LoginApp\\LoginApp\\history.txt";
    String tempFile = "C:\\Users\\ADMIN\\Documents\\NetBeansProjects\\LoginApp\\LoginApp\\tempfile.txt";

    Color DefaultColor, ClickedColor;

    private boolean showDataClicked = false;
    private boolean showDataClicked1 = false;

    /**
     * Creates new form Landing
     */
    public AdminDashboard() {
        initComponents();

        DefaultColor = new Color(26, 39, 51);
        ClickedColor = new Color(63, 106, 145);

        Costumeracc.setBackground(DefaultColor);
        Transactions.setBackground(DefaultColor);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane3 = new javax.swing.JDesktopPane();
        DbLogout = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        Panels = new javax.swing.JTabbedPane();
        Tab1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        database = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        Showdata = new javax.swing.JButton();
        Update = new javax.swing.JButton();
        Show = new javax.swing.JButton();
        Tab2 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        TransacTable = new javax.swing.JTable();
        Showdata1 = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        Trash = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TrashDatas = new javax.swing.JTable();
        Back = new javax.swing.JButton();
        Retrieve = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        update = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        Upstreet = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        Upcity = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        Upemail = new javax.swing.JTextField();
        jLabel46 = new javax.swing.JLabel();
        Upphone = new javax.swing.JTextField();
        UpbankNo = new javax.swing.JLabel();
        UpdateButton = new javax.swing.JButton();
        Upname = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Show1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        Costumeracc = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        Transactions = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DbLogout.setBackground(new java.awt.Color(63, 106, 145));
        DbLogout.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        DbLogout.setForeground(new java.awt.Color(255, 255, 255));
        DbLogout.setText("LOG OUT");
        DbLogout.setToolTipText("");
        DbLogout.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        DbLogout.setBorderPainted(false);
        DbLogout.setContentAreaFilled(false);
        DbLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DbLogoutActionPerformed(evt);
            }
        });

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/circle-user-round.png"))); // NOI18N

        jLabel14.setFont(new java.awt.Font("AvantGarde Bk BT", 0, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Simple Banking System");

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo (1).png"))); // NOI18N

        jDesktopPane3.setLayer(DbLogout, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(jLabel13, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(jLabel14, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(jLabel15, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane3Layout = new javax.swing.GroupLayout(jDesktopPane3);
        jDesktopPane3.setLayout(jDesktopPane3Layout);
        jDesktopPane3Layout.setHorizontalGroup(
            jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane3Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 589, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DbLogout)
                .addGap(17, 17, 17))
        );
        jDesktopPane3Layout.setVerticalGroup(
            jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addGroup(jDesktopPane3Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(DbLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel13)
                    .addGroup(jDesktopPane3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel14)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        getContentPane().add(jDesktopPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, -1));

        Tab1.setBackground(new java.awt.Color(138, 174, 206));

        database.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Bank NO.", "Complete Name", "Street", "City", "Email", "Mobile No."
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        database.getTableHeader().setReorderingAllowed(false);
        database.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                databaseMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(database);
        if (database.getColumnModel().getColumnCount() > 0) {
            database.getColumnModel().getColumn(0).setResizable(false);
            database.getColumnModel().getColumn(1).setResizable(false);
            database.getColumnModel().getColumn(2).setResizable(false);
            database.getColumnModel().getColumn(3).setResizable(false);
            database.getColumnModel().getColumn(4).setResizable(false);
            database.getColumnModel().getColumn(5).setResizable(false);
        }

        jPanel8.setBackground(new java.awt.Color(63, 106, 145));

        jLabel16.setBackground(new java.awt.Color(26, 39, 51));
        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 204, 204));
        jLabel16.setText("COSTUMER ACCOUNTS");

        jSeparator5.setForeground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel16)
                .addGap(41, 41, 41)
                .addComponent(jSeparator5, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))))
        );

        Showdata.setBackground(new java.awt.Color(63, 106, 145));
        Showdata.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        Showdata.setForeground(new java.awt.Color(255, 255, 255));
        Showdata.setText("Show datas");
        Showdata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowdataActionPerformed(evt);
            }
        });

        Update.setBackground(new java.awt.Color(63, 106, 145));
        Update.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        Update.setForeground(new java.awt.Color(255, 255, 255));
        Update.setText("UPDATE");
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });

        Show.setBackground(new java.awt.Color(63, 106, 145));
        Show.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        Show.setForeground(new java.awt.Color(255, 255, 255));
        Show.setText("Update Requests");
        Show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Tab1Layout = new javax.swing.GroupLayout(Tab1);
        Tab1.setLayout(Tab1Layout);
        Tab1Layout.setHorizontalGroup(
            Tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Tab1Layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(Tab1Layout.createSequentialGroup()
                .addGroup(Tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Tab1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 803, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Tab1Layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(Showdata, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Update, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Show)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Tab1Layout.setVerticalGroup(
            Tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Tab1Layout.createSequentialGroup()
                .addContainerGap(99, Short.MAX_VALUE)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Showdata, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Update, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Show, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );

        Panels.addTab("CA", Tab1);

        Tab2.setBackground(new java.awt.Color(138, 174, 206));

        jPanel9.setBackground(new java.awt.Color(63, 106, 145));

        jLabel17.setBackground(new java.awt.Color(26, 39, 51));
        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(204, 204, 204));
        jLabel17.setText("TRANSACTIONS");

        jSeparator6.setForeground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel17)
                .addGap(41, 41, 41)
                .addComponent(jSeparator6, javax.swing.GroupLayout.DEFAULT_SIZE, 595, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))))
        );

        TransacTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Account No.", "Type", "Amount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TransacTable.getTableHeader().setReorderingAllowed(false);
        TransacTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TransacTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TransacTable);
        if (TransacTable.getColumnModel().getColumnCount() > 0) {
            TransacTable.getColumnModel().getColumn(0).setResizable(false);
            TransacTable.getColumnModel().getColumn(1).setResizable(false);
            TransacTable.getColumnModel().getColumn(2).setResizable(false);
        }

        Showdata1.setBackground(new java.awt.Color(63, 106, 145));
        Showdata1.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        Showdata1.setForeground(new java.awt.Color(255, 255, 255));
        Showdata1.setText("Show datas");
        Showdata1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Showdata1ActionPerformed(evt);
            }
        });

        Delete.setBackground(new java.awt.Color(63, 106, 145));
        Delete.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        Delete.setForeground(new java.awt.Color(255, 255, 255));
        Delete.setText("Delete");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });

        Trash.setBackground(new java.awt.Color(63, 106, 145));
        Trash.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        Trash.setForeground(new java.awt.Color(255, 255, 255));
        Trash.setText("Go to trash");
        Trash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TrashActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Tab2Layout = new javax.swing.GroupLayout(Tab2);
        Tab2.setLayout(Tab2Layout);
        Tab2Layout.setHorizontalGroup(
            Tab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(Tab2Layout.createSequentialGroup()
                .addGap(178, 178, 178)
                .addComponent(Showdata1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(Trash)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(Tab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Tab2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 832, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        Tab2Layout.setVerticalGroup(
            Tab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Tab2Layout.createSequentialGroup()
                .addContainerGap(99, Short.MAX_VALUE)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(327, 327, 327)
                .addGroup(Tab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Showdata1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Trash, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54))
            .addGroup(Tab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Tab2Layout.createSequentialGroup()
                    .addGap(185, 185, 185)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(121, Short.MAX_VALUE)))
        );

        Panels.addTab("Transac", Tab2);

        TrashDatas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Account No.", "Type", "Amount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TrashDatas.getTableHeader().setReorderingAllowed(false);
        TrashDatas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TrashDatasMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(TrashDatas);
        if (TrashDatas.getColumnModel().getColumnCount() > 0) {
            TrashDatas.getColumnModel().getColumn(0).setResizable(false);
            TrashDatas.getColumnModel().getColumn(1).setResizable(false);
            TrashDatas.getColumnModel().getColumn(2).setResizable(false);
        }

        Back.setBackground(new java.awt.Color(63, 106, 145));
        Back.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        Back.setForeground(new java.awt.Color(255, 255, 255));
        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        Retrieve.setBackground(new java.awt.Color(63, 106, 145));
        Retrieve.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        Retrieve.setForeground(new java.awt.Color(255, 255, 255));
        Retrieve.setText("Retrieve");
        Retrieve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RetrieveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 781, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(21, 21, 21))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(Retrieve, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(87, 87, 87)))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(121, Short.MAX_VALUE)
                .addComponent(Back)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Retrieve, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );

        Panels.addTab("Deleted", jPanel1);

        update.setBackground(new java.awt.Color(255, 255, 255));

        jPanel10.setBackground(new java.awt.Color(63, 106, 145));

        jLabel18.setBackground(new java.awt.Color(26, 39, 51));
        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(204, 204, 204));
        jLabel18.setText("Account Update");

        jSeparator7.setForeground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel18)
                .addGap(41, 41, 41)
                .addComponent(jSeparator7, javax.swing.GroupLayout.DEFAULT_SIZE, 595, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))))
        );

        jLabel9.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Street");

        Upstreet.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 20)); // NOI18N
        Upstreet.setForeground(new java.awt.Color(51, 51, 51));
        Upstreet.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel10.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("City");

        Upcity.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 20)); // NOI18N
        Upcity.setForeground(new java.awt.Color(51, 51, 51));
        Upcity.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel19.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(51, 51, 51));
        jLabel19.setText("Email");

        jLabel20.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(51, 51, 51));
        jLabel20.setText("Phone Number");

        Upemail.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 20)); // NOI18N
        Upemail.setForeground(new java.awt.Color(51, 51, 51));
        Upemail.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel46.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(26, 39, 51));
        jLabel46.setText("ACCOUNT NO.");

        Upphone.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 20)); // NOI18N
        Upphone.setForeground(new java.awt.Color(51, 51, 51));
        Upphone.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        Upphone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                UpphoneKeyPressed(evt);
            }
        });

        UpbankNo.setBackground(new java.awt.Color(51, 153, 255));
        UpbankNo.setFont(new java.awt.Font("Swis721 Blk BT", 0, 24)); // NOI18N
        UpbankNo.setForeground(new java.awt.Color(51, 153, 255));
        UpbankNo.setText("BN000");

        UpdateButton.setBackground(new java.awt.Color(63, 106, 145));
        UpdateButton.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        UpdateButton.setForeground(new java.awt.Color(255, 255, 255));
        UpdateButton.setText("Update");
        UpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButtonActionPerformed(evt);
            }
        });

        Upname.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 20)); // NOI18N
        Upname.setForeground(new java.awt.Color(51, 51, 51));
        Upname.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Name");

        Show1.setBackground(new java.awt.Color(63, 106, 145));
        Show1.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        Show1.setForeground(new java.awt.Color(255, 255, 255));
        Show1.setText("Show");
        Show1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Show1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout updateLayout = new javax.swing.GroupLayout(update);
        update.setLayout(updateLayout);
        updateLayout.setHorizontalGroup(
            updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(updateLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(updateLayout.createSequentialGroup()
                        .addComponent(jLabel46)
                        .addGap(18, 18, 18)
                        .addComponent(UpbankNo)
                        .addContainerGap(547, Short.MAX_VALUE))
                    .addGroup(updateLayout.createSequentialGroup()
                        .addGroup(updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(Upname, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Upstreet, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Upcity, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, updateLayout.createSequentialGroup()
                                .addGroup(updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel19)
                                    .addComponent(Upemail)
                                    .addComponent(jLabel20)
                                    .addComponent(Upphone, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(78, 78, 78))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, updateLayout.createSequentialGroup()
                                .addComponent(UpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(111, 111, 111))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, updateLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Show1)
                .addGap(55, 55, 55))
        );
        updateLayout.setVerticalGroup(
            updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, updateLayout.createSequentialGroup()
                .addContainerGap(99, Short.MAX_VALUE)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UpbankNo))
                .addGap(18, 18, 18)
                .addGroup(updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(updateLayout.createSequentialGroup()
                        .addGroup(updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(updateLayout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Upemail, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(78, 78, 78))
                            .addGroup(updateLayout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Upphone, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(UpdateButton))
                    .addGroup(updateLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Upname, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addGap(0, 0, 0)
                        .addComponent(Upstreet, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Upcity, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21)
                .addComponent(Show1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 844, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 594, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        Panels.addTab("Update", jPanel2);

        getContentPane().add(Panels, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 820, 620));

        jPanel4.setBackground(new java.awt.Color(26, 39, 51));

        Costumeracc.setBackground(new java.awt.Color(26, 39, 51));
        Costumeracc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CostumeraccMousePressed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setText("Costumer Accounts");

        javax.swing.GroupLayout CostumeraccLayout = new javax.swing.GroupLayout(Costumeracc);
        Costumeracc.setLayout(CostumeraccLayout);
        CostumeraccLayout.setHorizontalGroup(
            CostumeraccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CostumeraccLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel11)
                .addContainerGap(62, Short.MAX_VALUE))
        );
        CostumeraccLayout.setVerticalGroup(
            CostumeraccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
        );

        Transactions.setBackground(new java.awt.Color(26, 39, 51));
        Transactions.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TransactionsMousePressed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        jLabel12.setText("Transactions");

        javax.swing.GroupLayout TransactionsLayout = new javax.swing.GroupLayout(Transactions);
        Transactions.setLayout(TransactionsLayout);
        TransactionsLayout.setHorizontalGroup(
            TransactionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TransactionsLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        TransactionsLayout.setVerticalGroup(
            TransactionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Costumeracc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Transactions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(178, 178, 178)
                .addComponent(Costumeracc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(Transactions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(213, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 270, 520));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CostumeraccMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CostumeraccMousePressed
        //Panel Transer.
        Costumeracc.setBackground(ClickedColor);
        Transactions.setBackground(DefaultColor);

        Panels.setSelectedIndex(0);

    }//GEN-LAST:event_CostumeraccMousePressed

    private void TransactionsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TransactionsMousePressed
        // Panel transfer
        Costumeracc.setBackground(DefaultColor);
        Transactions.setBackground(ClickedColor);

        Panels.setSelectedIndex(1);

    }//GEN-LAST:event_TransactionsMousePressed

    private void DbLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DbLogoutActionPerformed
        //transfer frame
        LogInPage lp = new LogInPage();
        lp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_DbLogoutActionPerformed

    private void databaseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_databaseMouseClicked
        //clear selection
        database.clearSelection();
    }//GEN-LAST:event_databaseMouseClicked

    private void ShowdataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowdataActionPerformed
        //Show data from textfile
        File f = new File("C:\\Users\\jowie james\\Documents\\NetBeansProjects\\LoginApp\\UsersAccount.txt");

        if (!showDataClicked) {
            showDataClicked = true;

            try {
                BufferedReader br = new BufferedReader(new FileReader(f));
                DefaultTableModel table = (DefaultTableModel) database.getModel();

                String[] rowData = new String[6];

                int rowIndex = 0;
                String line;
                while ((line = br.readLine()) != null) {
                    if (!line.contains("Passcode:") && !line.startsWith("------") && !line.contains("Balance:")) {
                        String[] row = line.split(": ");
                        if (row.length >= 2) {
                            rowData[rowIndex] = row[1];
                            rowIndex++;
                        }
                        if (rowIndex == 6) {
                            
                            table.addRow(rowData);
                            
                            rowIndex = 0;
                            Arrays.fill(rowData, null);
                        }
                    }
                }
                
                if (rowIndex > 0 && rowIndex < 6) {
                    String[] lastRowData = new String[6];
                    System.arraycopy(rowData, 0, lastRowData, 0, rowIndex);
                    table.addRow(lastRowData);
                }
            } catch (Exception ex) {
                Logger.getLogger(AdminDashboard.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_ShowdataActionPerformed

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        //Update button. Set data to textfield
        DefaultTableModel table = (DefaultTableModel) database.getModel();

        if (database.getSelectedRowCount() == 1) {
            Panels.setSelectedIndex(3);

            int selectedRow = database.getSelectedRow();
            String BankNo = (String) table.getValueAt(selectedRow, 0);
            String Name = (String) table.getValueAt(selectedRow, 1);
            String Street = (String) table.getValueAt(selectedRow, 2);
            String City = (String) table.getValueAt(selectedRow, 3);
            String Email = (String) table.getValueAt(selectedRow, 4);
            String Phone = (String) table.getValueAt(selectedRow, 5);

            UpbankNo.setText(BankNo);
            Upname.setText(Name);
            Upstreet.setText(Street);
            Upcity.setText(City);
            Upemail.setText(Email);
            Upphone.setText(Phone);

        } else {
            if (database.getRowCount() == 0) {
                JOptionPane.showMessageDialog(this, "Table is Empty.");
            } else {
                JOptionPane.showMessageDialog(this, "Please select  single row for delete.");
            }
        }

    }//GEN-LAST:event_UpdateActionPerformed

    private void ShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowActionPerformed
        // Show update request
        String getBankNo = RequestUpdate.reqBankno;
        String getName = RequestUpdate.reqName;
        String getStreet = RequestUpdate.reqStreet;
        String getCity = RequestUpdate.reqCity;
        String getEmail = RequestUpdate.reqEmail;
        String getPhoneN = RequestUpdate.reqPhoneN;

        JOptionPane.showMessageDialog(this, "BankNo: " + getBankNo + "\nName: " + getName + "\nStreet: " + getStreet
                + "\nCity: " + getCity + "\nEmail: " + getEmail + "\nPhoneN: "
                + getPhoneN, "Update Requests", JOptionPane.PLAIN_MESSAGE);

    }//GEN-LAST:event_ShowActionPerformed

    private void Showdata1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Showdata1ActionPerformed
        //Show history data from txtfile.
        File f = new File(historyData);

        if (!showDataClicked1) {
            showDataClicked1 = true;

            try {

                BufferedReader br = new BufferedReader(new FileReader(f));
                DefaultTableModel table = (DefaultTableModel) TransacTable.getModel();

                String line;
                while ((line = br.readLine()) != null) {
                    String[] row = line.split(", ");
                    boolean historyExists = false;
                    for (int j = 0; j < table.getRowCount(); j++) {

                        if (table.getValueAt(j, 0).equals(row[0]) && table.getValueAt(j, 1).equals(row[1])
                                && table.getValueAt(j, 2).equals(row[2])) {

                            historyExists = true;
                            break;
                        }
                    }
                    if (!historyExists) {
                        table.addRow(row);
                    }

                }

            } catch (Exception ex) {
                Logger.getLogger(AdminDashboard.class.getName()).log(Level.SEVERE, null, ex);
                System.out.println(ex);
            }
        }
    }//GEN-LAST:event_Showdata1ActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        // Remove data
        DefaultTableModel table = (DefaultTableModel) TransacTable.getModel();
        DefaultTableModel table1 = (DefaultTableModel) TrashDatas.getModel();
        if (TransacTable.getSelectedRowCount() == 1) {

            int selectedRow = TransacTable.getSelectedRow();
            String bankNo = (String) table.getValueAt(selectedRow, 0);
            String type = (String) table.getValueAt(selectedRow, 1);
            String amount = (String) table.getValueAt(selectedRow, 2);

            String[] datas = {bankNo, type, amount};

            table1.addRow(datas);
            table.removeRow(TransacTable.getSelectedRow());

        } else {
            if (TransacTable.getRowCount() == 0) {
                JOptionPane.showMessageDialog(this, "Table is Empty.");
            } else {
                JOptionPane.showMessageDialog(this, "Please select  single row for delete.");
            }
        }

    }//GEN-LAST:event_DeleteActionPerformed

    private void TransacTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TransacTableMouseClicked
        //clear selection
        TransacTable.clearSelection();
    }//GEN-LAST:event_TransacTableMouseClicked

    private void TrashDatasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TrashDatasMouseClicked
        //clear selection
        TrashDatas.clearSelection();
    }//GEN-LAST:event_TrashDatasMouseClicked

    private void TrashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TrashActionPerformed
        // Transfer Panel
        Panels.setSelectedIndex(2);
    }//GEN-LAST:event_TrashActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // Transfer Panel
        Panels.setSelectedIndex(1);
    }//GEN-LAST:event_BackActionPerformed

    private void RetrieveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RetrieveActionPerformed
        //Retrieve data
        
        DefaultTableModel table = (DefaultTableModel) TransacTable.getModel();
        DefaultTableModel table1 = (DefaultTableModel) TrashDatas.getModel();
        if (TrashDatas.getSelectedRowCount() == 1) {

            int selectedRow = TrashDatas.getSelectedRow();
            String bankNo = (String) table1.getValueAt(selectedRow, 0);
            String type = (String) table1.getValueAt(selectedRow, 1);
            String amount = (String) table1.getValueAt(selectedRow, 2);

            String[] datas = {bankNo, type, amount};

            table.addRow(datas);
            table1.removeRow(TrashDatas.getSelectedRow());

        } else {
            if (TrashDatas.getRowCount() == 0) {
                JOptionPane.showMessageDialog(this, "Table is Empty.");
            } else {
                JOptionPane.showMessageDialog(this, "Please select  single row for retrieve.");
            }
        }
    }//GEN-LAST:event_RetrieveActionPerformed

    private void UpphoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_UpphoneKeyPressed
        // Numbers Only

        char c = evt.getKeyChar();
        if (Character.isLetter(c)) {
            Upphone.setEditable(false);
        } else {
            Upphone.setEditable(true);
        }
    }//GEN-LAST:event_UpphoneKeyPressed

    private void UpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButtonActionPerformed
        // Update Button

        String Bnumber = UpbankNo.getText();
        String newName = Upname.getText();
        String newStreet = Upstreet.getText();
        String newCity = Upcity.getText();
        String newEmail = Upemail.getText();
        String newPhone = Upphone.getText();

        File f = new File(userAcc);
        File temp = new File(tempFile);
        //Updating the data
        try (BufferedReader br = new BufferedReader(new FileReader(temp));
                FileWriter fw = new FileWriter(f)) {

            String line;
            boolean found = false;
            boolean deleteNext = false;
            boolean isCurrentAccount = false;
            while ((line = br.readLine()) != null) {

                if (deleteNext) {
                    deleteNext = false;
                    continue;
                }
                String[] parts = line.split(": ");
                if (parts[0].equals("BankNo") && parts[1].equals(Bnumber)) {
                    isCurrentAccount = true;
                } else if (parts[0].equals("BankNo") && !parts[1].equals(Bnumber)) {
                    isCurrentAccount = false;
                }

                if (isCurrentAccount) {
                    if (parts[0].equals("BankNo")) {
                        fw.write("BankNo: " + Bnumber + System.getProperty("line.separator"));
                    } else if (parts[0].equals("Name")) {
                        fw.write("Name: " + newName + System.getProperty("line.separator"));
                    } else if (parts[0].equals("Street")) {
                        String newStreet2 = (newStreet.equals("")) ? parts[1] : newStreet;
                        fw.write("Street: " + newStreet2 + System.getProperty("line.separator"));
                    } else if (parts[0].equals("City")) {
                        String newCity2 = (newCity.equals("")) ? parts[1] : newCity;
                        fw.write("City: " + newCity2 + System.getProperty("line.separator"));
                    } else if (parts[0].equals("Email")) {
                        String newEmail2 = (newEmail.equals("")) ? parts[1] : newEmail;
                        fw.write("Email: " + newEmail2 + System.getProperty("line.separator"));
                    } else if (parts[0].equals("PhoneN")) {
                        String newPhone2 = (newPhone.equals("")) ? parts[1] : newPhone;
                        fw.write("PhoneN: " + newPhone2 + System.getProperty("line.separator"));
                    } else if (parts[0].equals("Balance")) {
                        fw.write(line + System.getProperty("line.separator"));
                    } else {
                        fw.write(line + System.getProperty("line.separator"));
                    }
                } else {
                    fw.write(line + System.getProperty("line.separator"));
                }

                if (parts[0].equals("BankNo") && parts[1].equals(Bnumber)) {
                    found = true;
                }

            }

            if (!found) {
                JOptionPane.showMessageDialog(this, "Bank number not found");
                return;
            }

            temp.delete();
            f.renameTo(temp);
            DefaultTableModel table = (DefaultTableModel) database.getModel();

            if (database.getSelectedRowCount() == 1) {
                String bnkNo = UpbankNo.getText();
                String owname = Upname.getText();
                String street = Upstreet.getText();
                String city = Upcity.getText();
                String email = Upemail.getText();
                String phone = Upphone.getText();

                table.setValueAt(bnkNo, database.getSelectedRow(), 0);
                table.setValueAt(owname, database.getSelectedRow(), 1);
                table.setValueAt(street, database.getSelectedRow(), 2);
                table.setValueAt(city, database.getSelectedRow(), 3);
                table.setValueAt(email, database.getSelectedRow(), 4);
                table.setValueAt(phone, database.getSelectedRow(), 5);
            }

            JOptionPane.showMessageDialog(this, "Data updated successfully");

        } catch (IOException ex) {
            Logger.getLogger(AdminDashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_UpdateButtonActionPerformed

    private void Show1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Show1ActionPerformed
        // Show the update request
        String getBankNo = RequestUpdate.reqBankno;
        String getName = RequestUpdate.reqName;
        String getStreet = RequestUpdate.reqStreet;
        String getCity = RequestUpdate.reqCity;
        String getEmail = RequestUpdate.reqEmail;
        String getPhoneN = RequestUpdate.reqPhoneN;

        JOptionPane.showMessageDialog(this, "BankNo: " + getBankNo + "\nName: " + getName + "\nStreet: " + getStreet
                + "\nCity: " + getCity + "\nEmail: " + getEmail + "\nPhoneN: "
                + getPhoneN, "Update Requests", JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_Show1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminDashboard().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JPanel Costumeracc;
    private javax.swing.JButton DbLogout;
    private javax.swing.JButton Delete;
    private javax.swing.JTabbedPane Panels;
    private javax.swing.JButton Retrieve;
    private javax.swing.JButton Show;
    private javax.swing.JButton Show1;
    private javax.swing.JButton Showdata;
    private javax.swing.JButton Showdata1;
    private javax.swing.JPanel Tab1;
    private javax.swing.JPanel Tab2;
    public javax.swing.JTable TransacTable;
    private javax.swing.JPanel Transactions;
    private javax.swing.JButton Trash;
    public javax.swing.JTable TrashDatas;
    public javax.swing.JLabel UpbankNo;
    javax.swing.JTextField Upcity;
    private javax.swing.JButton Update;
    private javax.swing.JButton UpdateButton;
    javax.swing.JTextField Upemail;
    javax.swing.JTextField Upname;
    javax.swing.JTextField Upphone;
    javax.swing.JTextField Upstreet;
    javax.swing.JTable database;
    private javax.swing.JDesktopPane jDesktopPane3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JPanel update;
    // End of variables declaration//GEN-END:variables
}
