/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SimpleBankingSystem;

import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jowie james
 */
public class CreateAcc extends javax.swing.JFrame {

    String userAcc = "C:\\Users\\ADMIN\\Documents\\NetBeansProjects\\LoginApp\\LoginApp\\UsersAccount.txt";
    String AdminAcc = "C:\\Users\\ADMIN\\Documents\\NetBeansProjects\\LoginApp\\LoginApp\\AdminAccount.txt";
    String temporary = "C:\\Users\\ADMIN\\Documents\\NetBeansProjects\\LoginApp\\LoginApp\\tempfile.txt";

    public CreateAcc() {
        initComponents();
        increment.setText(String.valueOf(BankNumber.BankNumb));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSignUp = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLogIn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        CName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        CStreet = new javax.swing.JTextField();
        CCity = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        CEmail = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        BankNo = new javax.swing.JLabel();
        CPhoneN = new javax.swing.JTextField();
        increment = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        CPasscode = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        CCpasscode = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("REGISTER");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Simple Banking System");

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Bank No.");

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Name");

        jSignUp.setBackground(new java.awt.Color(63, 106, 145));
        jSignUp.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        jSignUp.setForeground(new java.awt.Color(255, 255, 255));
        jSignUp.setText("SIGN UP");
        jSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSignUpActionPerformed(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(51, 51, 51));

        jLogIn.setBackground(new java.awt.Color(255, 255, 255));
        jLogIn.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jLogIn.setForeground(new java.awt.Color(88, 146, 199));
        jLogIn.setText("Log In");
        jLogIn.setBorder(null);
        jLogIn.setBorderPainted(false);
        jLogIn.setContentAreaFilled(false);
        jLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLogInActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Already have an account?");

        CName.setBackground(new java.awt.Color(255, 255, 255));
        CName.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 20)); // NOI18N
        CName.setForeground(new java.awt.Color(51, 51, 51));
        CName.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Street");

        CStreet.setBackground(new java.awt.Color(255, 255, 255));
        CStreet.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 20)); // NOI18N
        CStreet.setForeground(new java.awt.Color(51, 51, 51));
        CStreet.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        CCity.setBackground(new java.awt.Color(255, 255, 255));
        CCity.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 20)); // NOI18N
        CCity.setForeground(new java.awt.Color(51, 51, 51));
        CCity.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("City");

        jLabel9.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Email");

        CEmail.setBackground(new java.awt.Color(255, 255, 255));
        CEmail.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 20)); // NOI18N
        CEmail.setForeground(new java.awt.Color(51, 51, 51));
        CEmail.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel10.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("Phone Number");

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo (1).png"))); // NOI18N

        BankNo.setBackground(new java.awt.Color(51, 153, 255));
        BankNo.setFont(new java.awt.Font("Swis721 Blk BT", 0, 24)); // NOI18N
        BankNo.setForeground(new java.awt.Color(51, 153, 255));
        BankNo.setText("BN00");

        CPhoneN.setBackground(new java.awt.Color(255, 255, 255));
        CPhoneN.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 20)); // NOI18N
        CPhoneN.setForeground(new java.awt.Color(51, 51, 51));
        CPhoneN.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        CPhoneN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CPhoneNKeyPressed(evt);
            }
        });

        increment.setBackground(new java.awt.Color(51, 153, 255));
        increment.setFont(new java.awt.Font("Swis721 Blk BT", 0, 24)); // NOI18N
        increment.setForeground(new java.awt.Color(51, 153, 255));
        increment.setText("1");

        jLabel13.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jLabel13.setText("Passcode");

        CPasscode.setBackground(new java.awt.Color(255, 255, 255));
        CPasscode.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 20)); // NOI18N
        CPasscode.setForeground(new java.awt.Color(51, 51, 51));
        CPasscode.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel14.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 51, 51));
        jLabel14.setText("Confirm Passcode");

        CCpasscode.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        CCpasscode.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(CName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(CStreet, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(CCity, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(BankNo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(increment))
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1)))
                        .addGap(46, 46, 46)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel9)
                            .addComponent(CEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                            .addComponent(jLabel10)
                            .addComponent(CPhoneN, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                            .addComponent(jLabel13)
                            .addComponent(CPasscode, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                            .addComponent(jLabel14)
                            .addComponent(CCpasscode)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(145, 145, 145)
                                .addComponent(jLabel5))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(182, 182, 182)
                                .addComponent(jLogIn, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(49, 49, 49)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(20, 20, 20)
                                .addComponent(increment, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(CEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BankNo))))
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CName, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CPhoneN, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(0, 0, 0)
                        .addComponent(CStreet, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CPasscode, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CCity, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CCpasscode, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jLabel5)
                .addGap(6, 6, 6)
                .addComponent(jLogIn)
                .addGap(33, 33, 33))
        );

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo (1)_1.png"))); // NOI18N

        jLabel12.setFont(new java.awt.Font("Futura Md BT", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Simple Banking System");

        jDesktopPane1.setLayer(jPanel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel12, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel6))
                    .addComponent(jLabel12))
                .addGap(74, 74, 74))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(204, 204, 204)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 630));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSignUpActionPerformed
        //SignUp button
        String Bnumber = BankNo.getText();
        String Name = CName.getText();
        String Street = CStreet.getText();
        String City = CCity.getText();
        String Email = CEmail.getText();
        String PhoneN = CPhoneN.getText();
        String Passcode = CPasscode.getText();
        String ConfPass = CCpasscode.getText();

        File f = new File(userAcc);
        File f2 = new File(temporary);

        if (Name.isEmpty() || Street.isEmpty() || City.isEmpty() || Email.isEmpty() || PhoneN.isEmpty() || Passcode.isEmpty() || ConfPass.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill out the data");
            return;
        }
        if (PhoneN.length() != 11 || !PhoneN.matches("\\d+")) {
            JOptionPane.showMessageDialog(this, "Phone number must be 11 digits");
            return;
        } if (!Passcode.matches(ConfPass)) {
            JOptionPane.showMessageDialog(this, "Passcode doesn't match");
        } else {

            try {

                FileWriter fw = new FileWriter(f, true);
                FileWriter wr = new FileWriter(f2, true);

                int currentValue = Integer.parseInt(increment.getText());

                fw.write("BankNo" + ": " + Bnumber + currentValue);
                fw.write(System.getProperty("line.separator"));
                fw.write("Name" + ": " + Name);
                fw.write(System.getProperty("line.separator"));
                fw.write("Street" + ": " + Street);
                fw.write(System.getProperty("line.separator"));
                fw.write("City" + ": " + City);
                fw.write(System.getProperty("line.separator"));
                fw.write("Email" + ": " + Email);
                fw.write(System.getProperty("line.separator"));
                fw.write("PhoneN" + ": " + PhoneN + System.getProperty("line.separator") + "Balance" + ": " + "0.0" + System.getProperty("line.separator"));
                fw.write("Passcode" + ": " + Passcode);
                fw.write(System.getProperty("line.separator"));
                fw.write("------");
                fw.write(System.getProperty("line.separator"));

                fw.close();
                
                wr.write("BankNo" + ": " + Bnumber + currentValue);
                wr.write(System.getProperty("line.separator"));
                wr.write("Name" + ": " + Name);
                wr.write(System.getProperty("line.separator"));
                wr.write("Street" + ": " + Street);
                wr.write(System.getProperty("line.separator"));
                wr.write("City" + ": " + City);
                wr.write(System.getProperty("line.separator"));
                wr.write("Email" + ": " + Email);
                wr.write(System.getProperty("line.separator"));
                wr.write("PhoneN" + ": " + PhoneN + System.getProperty("line.separator") + "Balance" + ": " + "0.0" + System.getProperty("line.separator"));
                wr.write("Passcode" + ": " + Passcode);
                wr.write(System.getProperty("line.separator"));
                wr.write("------");
                wr.write(System.getProperty("line.separator"));

                wr.close();
                

                JOptionPane.showMessageDialog(this, "You have successfully created the Account!");

                increment.setText(String.valueOf(currentValue + 1));
                CName.setText("");
                CStreet.setText("");
                CCity.setText("");
                CEmail.setText("");
                CPhoneN.setText("");
                CPasscode.setText("");
                CCpasscode.setText("");

                BankNumber.BankNumb = Integer.parseInt(increment.getText());

            } catch (IOException ex) {
                Logger.getLogger(CreateAcc.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_jSignUpActionPerformed

    private void jLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLogInActionPerformed
        LogInPage lp = new LogInPage();
        lp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLogInActionPerformed

    private void CPhoneNKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CPhoneNKeyPressed
        // Numbers only

        char c = evt.getKeyChar();
        if (Character.isLetter(c)) {
            CPhoneN.setEditable(false);
        } else {
            CPhoneN.setEditable(true);
        }
    }//GEN-LAST:event_CPhoneNKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateAcc.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateAcc.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateAcc.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateAcc.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateAcc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BankNo;
    private javax.swing.JTextField CCity;
    private javax.swing.JPasswordField CCpasscode;
    private javax.swing.JTextField CEmail;
    javax.swing.JTextField CName;
    private javax.swing.JTextField CPasscode;
    private javax.swing.JTextField CPhoneN;
    private javax.swing.JTextField CStreet;
    public static javax.swing.JLabel increment;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton jLogIn;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton jSignUp;
    // End of variables declaration//GEN-END:variables
}
