/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SimpleBankingSystem;

import java.awt.Color;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import java.util.HashMap;
import java.util.Map;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author jowie james
 */
public class DashBoard extends javax.swing.JFrame {

    Color DefaultColor, ClickedColor;

    String usersFilePath = "C:\\Users\\ADMIN\\Documents\\NetBeansProjects\\LoginApp\\LoginApp\\AdminAccount.txt";
    String customerAccountsFilePath = "C:\\Users\\ADMIN\\Documents\\NetBeansProjects\\LoginApp\\LoginApp\\UsersAccount.txt";
    ArrayList<String> all_usernames = new ArrayList<>();
    ArrayList<String> all_bankNo = new ArrayList<>();
    ArrayList<String> all_balance = new ArrayList<>();
    Map<String, String> bankNoANDbalance = new HashMap<>();
    Map<String, String> usernamesANDpasscode = new HashMap<>();
    Map<String, String> bankNoANDnames = new HashMap<>();

    public DashBoard() {
        initComponents();

        DefaultColor = new Color(26, 39, 51);
        ClickedColor = new Color(63, 106, 145);

        CheckBal.setBackground(DefaultColor);
        Deposit.setBackground(DefaultColor);
        Withdrawal.setBackground(DefaultColor);
        LogOut.setBackground(DefaultColor);

    }

    public void autoBankN() {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panel1 = new java.awt.Panel();
        jDesktopPane3 = new javax.swing.JDesktopPane();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        CheckBal = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        Deposit = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        Withdrawal = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        LogOut = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        Panels = new javax.swing.JTabbedPane();
        PcheckBal = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel5 = new javax.swing.JPanel();
        cbEnter = new javax.swing.JButton();
        cbCancel = new javax.swing.JButton();
        jLabel38 = new javax.swing.JLabel();
        jPanel36 = new javax.swing.JPanel();
        jLabel93 = new javax.swing.JLabel();
        cbBal = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        cBankNo = new javax.swing.JTextField();
        cFName = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        Pdeposit = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jPanel6 = new javax.swing.JPanel();
        dEnter = new javax.swing.JButton();
        dDepositButton = new javax.swing.JButton();
        jLabel44 = new javax.swing.JLabel();
        jPanel37 = new javax.swing.JPanel();
        jLabel95 = new javax.swing.JLabel();
        dDeposit = new javax.swing.JTextField();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        dAccNo = new javax.swing.JTextField();
        DdpBal = new javax.swing.JLabel();
        dCName = new javax.swing.JLabel();
        dClear = new javax.swing.JButton();
        Pwithdrawal = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jPanel9 = new javax.swing.JPanel();
        wEnterButton = new javax.swing.JButton();
        wDepositButton = new javax.swing.JButton();
        jLabel45 = new javax.swing.JLabel();
        jPanel38 = new javax.swing.JPanel();
        jLabel96 = new javax.swing.JLabel();
        wWithdraw = new javax.swing.JTextField();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        WdpFName = new javax.swing.JLabel();
        wAccNo = new javax.swing.JTextField();
        WdpBal = new javax.swing.JLabel();
        dClear1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel1.setBackground(new java.awt.Color(40, 75, 105));

        jLabel3.setFont(new java.awt.Font("AvantGarde Bk BT", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Simple Banking System");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo (1).png"))); // NOI18N

        jDesktopPane3.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane3Layout = new javax.swing.GroupLayout(jDesktopPane3);
        jDesktopPane3.setLayout(jDesktopPane3Layout);
        jDesktopPane3Layout.setHorizontalGroup(
            jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane3Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap(773, Short.MAX_VALUE))
        );
        jDesktopPane3Layout.setVerticalGroup(
            jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane3Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(31, 31, 31))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane3Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18))))
        );

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addComponent(jDesktopPane3)
                .addContainerGap())
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane3)
        );

        jPanel1.add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1130, 100));

        jPanel2.setBackground(new java.awt.Color(26, 39, 51));

        CheckBal.setBackground(new java.awt.Color(26, 39, 51));
        CheckBal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CheckBalMousePressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Check Balance");

        javax.swing.GroupLayout CheckBalLayout = new javax.swing.GroupLayout(CheckBal);
        CheckBal.setLayout(CheckBalLayout);
        CheckBalLayout.setHorizontalGroup(
            CheckBalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CheckBalLayout.createSequentialGroup()
                .addContainerGap(71, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(71, 71, 71))
        );
        CheckBalLayout.setVerticalGroup(
            CheckBalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
        );

        Deposit.setBackground(new java.awt.Color(26, 39, 51));
        Deposit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                DepositMousePressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Deposit");

        javax.swing.GroupLayout DepositLayout = new javax.swing.GroupLayout(Deposit);
        Deposit.setLayout(DepositLayout);
        DepositLayout.setHorizontalGroup(
            DepositLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DepositLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(98, 98, 98))
        );
        DepositLayout.setVerticalGroup(
            DepositLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
        );

        Withdrawal.setBackground(new java.awt.Color(26, 39, 51));
        Withdrawal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                WithdrawalMousePressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Withdrawal");

        javax.swing.GroupLayout WithdrawalLayout = new javax.swing.GroupLayout(Withdrawal);
        Withdrawal.setLayout(WithdrawalLayout);
        WithdrawalLayout.setHorizontalGroup(
            WithdrawalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, WithdrawalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(82, 82, 82))
        );
        WithdrawalLayout.setVerticalGroup(
            WithdrawalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
        );

        LogOut.setBackground(new java.awt.Color(26, 39, 51));
        LogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LogOutMousePressed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 204, 204));
        jLabel16.setText("Log Out");

        javax.swing.GroupLayout LogOutLayout = new javax.swing.GroupLayout(LogOut);
        LogOut.setLayout(LogOutLayout);
        LogOutLayout.setHorizontalGroup(
            LogOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LogOutLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addGap(97, 97, 97))
        );
        LogOutLayout.setVerticalGroup(
            LogOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CheckBal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Deposit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Withdrawal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(LogOut, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(CheckBal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(Deposit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(Withdrawal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(LogOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(248, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 260, 630));

        PcheckBal.setBackground(new java.awt.Color(138, 174, 206));

        jPanel7.setBackground(new java.awt.Color(63, 106, 145));

        jLabel17.setBackground(new java.awt.Color(26, 39, 51));
        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(204, 204, 204));
        jLabel17.setText("CHECK BALANCE");

        jSeparator2.setForeground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel17)
                .addGap(41, 41, 41)
                .addComponent(jSeparator2))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))))
        );

        jPanel5.setForeground(new java.awt.Color(60, 63, 65));

        cbEnter.setBackground(new java.awt.Color(63, 106, 145));
        cbEnter.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        cbEnter.setForeground(new java.awt.Color(255, 255, 255));
        cbEnter.setText("ENTER");
        cbEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEnterActionPerformed(evt);
            }
        });

        cbCancel.setBackground(new java.awt.Color(63, 106, 145));
        cbCancel.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        cbCancel.setForeground(new java.awt.Color(255, 255, 255));
        cbCancel.setText("CLEAR");
        cbCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCancelActionPerformed(evt);
            }
        });

        jLabel38.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(26, 39, 51));
        jLabel38.setText("ENTER THE ACCOUNT NO.");

        jPanel36.setBackground(new java.awt.Color(255, 255, 255));
        jPanel36.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel93.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        jLabel93.setForeground(new java.awt.Color(84, 120, 152));
        jLabel93.setText("Php");

        cbBal.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        cbBal.setForeground(new java.awt.Color(26, 39, 51));
        cbBal.setText("00.00");

        javax.swing.GroupLayout jPanel36Layout = new javax.swing.GroupLayout(jPanel36);
        jPanel36.setLayout(jPanel36Layout);
        jPanel36Layout.setHorizontalGroup(
            jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel36Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel93)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbBal)
                .addContainerGap(215, Short.MAX_VALUE))
        );
        jPanel36Layout.setVerticalGroup(
            jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel36Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel93)
                    .addComponent(cbBal))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jLabel41.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(84, 120, 152));
        jLabel41.setText("Your balance is");

        cBankNo.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        cFName.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        cFName.setForeground(new java.awt.Color(26, 39, 51));

        jLabel49.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(26, 39, 51));
        jLabel49.setText("Owner's Name:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(351, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel41)
                        .addComponent(jPanel36, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel38)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cBankNo)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(cbEnter, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(46, 46, 46))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel49)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cFName, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cBankNo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbEnter)
                    .addComponent(cbCancel))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel49, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(cFName, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(44, 44, 44)
                .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel36, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(218, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PcheckBalLayout = new javax.swing.GroupLayout(PcheckBal);
        PcheckBal.setLayout(PcheckBalLayout);
        PcheckBalLayout.setHorizontalGroup(
            PcheckBalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PcheckBalLayout.setVerticalGroup(
            PcheckBalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PcheckBalLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Panels.addTab("tab2", PcheckBal);

        Pdeposit.setBackground(new java.awt.Color(138, 174, 206));

        jPanel10.setBackground(new java.awt.Color(63, 106, 145));

        jLabel27.setBackground(new java.awt.Color(26, 39, 51));
        jLabel27.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(204, 204, 204));
        jLabel27.setText("DEPOSIT");

        jSeparator3.setForeground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel27)
                .addGap(41, 41, 41)
                .addComponent(jSeparator3, javax.swing.GroupLayout.DEFAULT_SIZE, 698, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel27)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))))
        );

        jPanel6.setForeground(new java.awt.Color(60, 63, 65));

        dEnter.setBackground(new java.awt.Color(63, 106, 145));
        dEnter.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        dEnter.setForeground(new java.awt.Color(255, 255, 255));
        dEnter.setText("ENTER");
        dEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dEnterActionPerformed(evt);
            }
        });

        dDepositButton.setBackground(new java.awt.Color(63, 106, 145));
        dDepositButton.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        dDepositButton.setForeground(new java.awt.Color(255, 255, 255));
        dDepositButton.setText("DEPOSIT");
        dDepositButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dDepositButtonActionPerformed(evt);
            }
        });

        jLabel44.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(26, 39, 51));
        jLabel44.setText("ENTER THE ACCOUNT NO.");

        jPanel37.setBackground(new java.awt.Color(255, 255, 255));
        jPanel37.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel95.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        jLabel95.setForeground(new java.awt.Color(84, 120, 152));
        jLabel95.setText("Php");

        dDeposit.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        dDeposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dDepositActionPerformed(evt);
            }
        });
        dDeposit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                dDepositKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel37Layout = new javax.swing.GroupLayout(jPanel37);
        jPanel37.setLayout(jPanel37Layout);
        jPanel37Layout.setHorizontalGroup(
            jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel37Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel95)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel37Layout.setVerticalGroup(
            jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel37Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel37Layout.createSequentialGroup()
                        .addComponent(jLabel95)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(dDeposit, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel47.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(84, 120, 152));
        jLabel47.setText("Your balance now is Php");

        jLabel48.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(26, 39, 51));
        jLabel48.setText("Owner's Name:");

        dAccNo.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        DdpBal.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        DdpBal.setForeground(new java.awt.Color(0, 0, 0));
        DdpBal.setText("00.00");

        dCName.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        dCName.setForeground(new java.awt.Color(26, 39, 51));

        dClear.setBackground(new java.awt.Color(63, 106, 145));
        dClear.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        dClear.setForeground(new java.awt.Color(255, 255, 255));
        dClear.setText("CLEAR");
        dClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel48)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dCName, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel44)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(dEnter, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dClear, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(dAccNo)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel47)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(DdpBal))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jPanel37, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(dDepositButton, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(127, 127, 127)))
                .addGap(46, 46, 46))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dAccNo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dEnter)
                    .addComponent(dClear))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel48, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(dCName, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(69, 69, 69)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jPanel37, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(dDepositButton)
                        .addGap(19, 19, 19)))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel47, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DdpBal, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(194, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PdepositLayout = new javax.swing.GroupLayout(Pdeposit);
        Pdeposit.setLayout(PdepositLayout);
        PdepositLayout.setHorizontalGroup(
            PdepositLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PdepositLayout.setVerticalGroup(
            PdepositLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PdepositLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Panels.addTab("tab3", Pdeposit);

        Pwithdrawal.setBackground(new java.awt.Color(138, 174, 206));

        jPanel15.setBackground(new java.awt.Color(63, 106, 145));

        jLabel33.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(204, 204, 204));
        jLabel33.setText("WITHDRAWAL");

        jSeparator6.setForeground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel33)
                .addGap(41, 41, 41)
                .addComponent(jSeparator6, javax.swing.GroupLayout.DEFAULT_SIZE, 638, Short.MAX_VALUE))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                        .addComponent(jLabel33)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))))
        );

        jPanel9.setForeground(new java.awt.Color(60, 63, 65));

        wEnterButton.setBackground(new java.awt.Color(63, 106, 145));
        wEnterButton.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        wEnterButton.setForeground(new java.awt.Color(255, 255, 255));
        wEnterButton.setText("ENTER");
        wEnterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wEnterButtonActionPerformed(evt);
            }
        });

        wDepositButton.setBackground(new java.awt.Color(63, 106, 145));
        wDepositButton.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        wDepositButton.setForeground(new java.awt.Color(255, 255, 255));
        wDepositButton.setText("DEPOSIT");

        jLabel45.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(26, 39, 51));
        jLabel45.setText("ENTER THE ACCOUNT NO.");

        jPanel38.setBackground(new java.awt.Color(255, 255, 255));
        jPanel38.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel96.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        jLabel96.setForeground(new java.awt.Color(84, 120, 152));
        jLabel96.setText("Php");

        wWithdraw.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        wWithdraw.setText("00.00");
        wWithdraw.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                wWithdrawKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel38Layout = new javax.swing.GroupLayout(jPanel38);
        jPanel38.setLayout(jPanel38Layout);
        jPanel38Layout.setHorizontalGroup(
            jPanel38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel38Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel96)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(wWithdraw, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel38Layout.setVerticalGroup(
            jPanel38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel38Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel38Layout.createSequentialGroup()
                        .addComponent(jLabel96)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(wWithdraw, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel50.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(84, 120, 152));
        jLabel50.setText("Available balance is Php");

        jLabel51.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(26, 39, 51));
        jLabel51.setText("Owner's Name:");

        WdpFName.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        WdpFName.setForeground(new java.awt.Color(26, 39, 51));

        wAccNo.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        WdpBal.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        WdpBal.setForeground(new java.awt.Color(0, 0, 0));
        WdpBal.setText("00.00");

        dClear1.setBackground(new java.awt.Color(63, 106, 145));
        dClear1.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        dClear1.setForeground(new java.awt.Color(255, 255, 255));
        dClear1.setText("CLEAR");
        dClear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dClear1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel45)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(wEnterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dClear1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(wAccNo)))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabel50)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(WdpBal))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jPanel38, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(wDepositButton, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(127, 127, 127)))
                .addGap(46, 46, 46))
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel51)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(WdpFName, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wAccNo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel45, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wEnterButton)
                    .addComponent(dClear1))
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel51, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(WdpFName, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(42, 42, 42)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel50, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WdpBal, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel38, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addComponent(wDepositButton)
                        .addGap(13, 13, 13)))
                .addContainerGap(221, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PwithdrawalLayout = new javax.swing.GroupLayout(Pwithdrawal);
        Pwithdrawal.setLayout(PwithdrawalLayout);
        PwithdrawalLayout.setHorizontalGroup(
            PwithdrawalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PwithdrawalLayout.setVerticalGroup(
            PwithdrawalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PwithdrawalLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Panels.addTab("tab4", Pwithdrawal);

        jPanel1.add(Panels, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, 870, 680));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1123, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void WithdrawalMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_WithdrawalMousePressed
        //withdrawal

        CheckBal.setBackground(DefaultColor);
        Deposit.setBackground(DefaultColor);
        Withdrawal.setBackground(ClickedColor);
        LogOut.setBackground(DefaultColor);

        Panels.setSelectedIndex(2);

    }//GEN-LAST:event_WithdrawalMousePressed

    private void DepositMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DepositMousePressed
        //deposit

        CheckBal.setBackground(DefaultColor);
        Deposit.setBackground(ClickedColor);
        Withdrawal.setBackground(DefaultColor);
        LogOut.setBackground(DefaultColor);

        Panels.setSelectedIndex(1);

    }//GEN-LAST:event_DepositMousePressed

    private void CheckBalMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CheckBalMousePressed
        //checkBal

        CheckBal.setBackground(ClickedColor);
        Deposit.setBackground(DefaultColor);
        Withdrawal.setBackground(DefaultColor);
        LogOut.setBackground(DefaultColor);

        Panels.setSelectedIndex(0);

    }//GEN-LAST:event_CheckBalMousePressed

    private void LogOutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogOutMousePressed
        //logout

        CheckBal.setBackground(DefaultColor);
        Deposit.setBackground(DefaultColor);
        Withdrawal.setBackground(DefaultColor);
        LogOut.setBackground(ClickedColor);

        LogInPage lp = new LogInPage();
        lp.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_LogOutMousePressed

    private void cbEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEnterActionPerformed
        //getAccount

        File f = new File(customerAccountsFilePath);
        String bankNo = cBankNo.getText();
        String bnkN = "";
        String OwnerName = "";
        String bal = "";

        if (bankNo.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please input a Bank No.");
        } else {

            try {

                FileReader fr = new FileReader(f);
                BufferedReader br = new BufferedReader(fr);

                Object[] lines = br.lines().toArray();
                for (int i = 0; i < lines.length; i++) {
                    String[] row = lines[i].toString().split(": ");
                    if (row[0].equals("BankNo")) {
                        bnkN = row[1];
                        all_bankNo.add(bnkN);
                    } else if (row[0].equals("Name")) {
                        OwnerName = row[1];
                        all_usernames.add(OwnerName);
                    } else if (row[0].equals("Balance")) {
                        bal = row[1];
                        all_balance.add(bal);
                    }
                    if (!bnkN.equals("") && !OwnerName.equals("") && !bal.equals("")) {
                        bankNoANDnames.put(bnkN, OwnerName);
                    }
                    for (String n : bankNoANDnames.keySet()) {
                        if (n.equals(bankNo)) {
                            if (bankNoANDnames.get(n).equals(OwnerName)) {
                                cFName.setText(OwnerName);
                                cbBal.setText(bal);

                            }
                        }
                    }
                }
                System.out.println(all_bankNo);
                System.out.println(all_usernames);
                System.out.println(all_balance);

            } catch (FileNotFoundException ex) {
                Logger.getLogger(DashBoard.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_cbEnterActionPerformed

    private void wEnterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wEnterButtonActionPerformed
        // TODO add your handling code here:
        String bankNo = wAccNo.getText();
        File f = new File(customerAccountsFilePath);
        String bnkN = "";
        String OwnerName = "";
        String bal = "";

        if (bankNo.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please input a Bank No.");
        } else {

            try {

                FileReader fr = new FileReader(f);
                BufferedReader br = new BufferedReader(fr);

                Object[] lines = br.lines().toArray();
                for (int i = 0; i < lines.length; i++) {
                    String[] row = lines[i].toString().split(": ");
                    if (row[0].equals("BankNo")) {
                        bnkN = row[1];
                        all_bankNo.add(bnkN);
                    } else if (row[0].equals("Name")) {
                        OwnerName = row[1];
                    }
                    if (!bnkN.equals("") && !OwnerName.equals("") && !bal.equals("")) {
                        bankNoANDnames.put(bnkN, OwnerName);
                    }

                    for (String n : bankNoANDnames.keySet()) {
                        if (n.equals(bankNo)) {
                            if (bankNoANDnames.get(n).equals(OwnerName)) {
                                WdpFName.setText(OwnerName);
                                wWithdraw.setText(bal);

                            }
                        }
                    }
                }

            } catch (FileNotFoundException ex) {
                Logger.getLogger(DashBoard.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_wEnterButtonActionPerformed

    private void cbCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCancelActionPerformed
        // clear
        cBankNo.setText("");
        cFName.setText("");
        cbBal.setText("00.00");
    }//GEN-LAST:event_cbCancelActionPerformed

    private void dClear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dClear1ActionPerformed
        // TODO add your handling code here:
        wAccNo.setText("");
        WdpFName.setText("");
        wWithdraw.setText("00.00");
    }//GEN-LAST:event_dClear1ActionPerformed

    private void dDepositButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dDepositButtonActionPerformed
        // Create a deposit function here
        String searchId = dAccNo.getText();
        String deposit = dDeposit.getText();
        String f = "customerAccountsFilePath";

        ArrayList<String> tempArray = new ArrayList<>();

        try {
            try {
                FileReader fr = new FileReader(f);
                Scanner reader = new Scanner(fr);
                String line;
                String[] lineArr;

                while ((line = reader.nextLine()) != null) {
                    lineArr = line.split(System.getProperty("line.separator") + ":");
                    if (lineArr[0].equals(searchId)) {
                        tempArray.add(
                                lineArr[0] + ","
                                + lineArr[1] + ","
                                + lineArr[2] + ","
                                + lineArr[3] + ","
                                + deposit);

                    } else {
                        tempArray.add(line);
                    }
                }
                fr.close();

            } catch (Exception e) {

            }
        } catch (Exception e) {

        }
        try {
            try (PrintWriter pw = new PrintWriter(f)) {

                for (String str : tempArray) {
                    pw.println(str);
                }
                pw.close();

            } catch (Exception e) {

            }
        } catch (Exception e) {

        }


    }//GEN-LAST:event_dDepositButtonActionPerformed

    private void dDepositKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dDepositKeyPressed
        // disableletter
        char c = evt.getKeyChar();
        if (Character.isLetter(c)) {
            dDeposit.setEditable(false);
        } else {
            dDeposit.setEditable(true);
        }
    }//GEN-LAST:event_dDepositKeyPressed

    private void wWithdrawKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_wWithdrawKeyPressed
        // disableletter
        char c = evt.getKeyChar();
        if (Character.isLetter(c)) {
            wWithdraw.setEditable(false);
        } else {
            wWithdraw.setEditable(true);
        }
    }//GEN-LAST:event_wWithdrawKeyPressed

    private void dDepositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dDepositActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dDepositActionPerformed

    private void dClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dClearActionPerformed
        // TODO add your handling code here:
        dAccNo.setText("");
        dCName.setText("");
        dDeposit.setText("00.00");
    }//GEN-LAST:event_dClearActionPerformed

    private void dEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dEnterActionPerformed
        // TODO add your handling code here:
        String bankNo = dAccNo.getText();
        File f = new File(customerAccountsFilePath);
        String bnkN = "";
        String OwnerName = "";
        String bal = "";

        if (bankNo.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please input a Bank No.");
        } else {

            try {

                FileReader fr = new FileReader(f);
                BufferedReader br = new BufferedReader(fr);

                Object[] lines = br.lines().toArray();
                for (int i = 0; i < lines.length; i++) {
                    String[] row = lines[i].toString().split(": ");
                    if (row[0].equals("BankNo")) {
                        bnkN = row[1];
                        all_bankNo.add(bnkN);
                    } else if (row[0].equals("Name")) {
                        OwnerName = row[1];
                    }
                    if (!bnkN.equals("") && !OwnerName.equals("") && !bal.equals("")) {
                        bankNoANDnames.put(bnkN, OwnerName);
                    }

                    for (String k : bankNoANDnames.keySet()) {
                        if (k.equals(bankNo)) {
                            if (bankNoANDnames.get(k).equals(OwnerName)) {
                                dCName.setText(OwnerName);

                            }
                        }
                    }
                }

            } catch (FileNotFoundException ex) {
                Logger.getLogger(DashBoard.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_dEnterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashBoard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CheckBal;
    private javax.swing.JLabel DdpBal;
    private javax.swing.JPanel Deposit;
    private javax.swing.JPanel LogOut;
    private javax.swing.JTabbedPane Panels;
    private javax.swing.JPanel PcheckBal;
    private javax.swing.JPanel Pdeposit;
    private javax.swing.JPanel Pwithdrawal;
    private javax.swing.JLabel WdpBal;
    private javax.swing.JLabel WdpFName;
    private javax.swing.JPanel Withdrawal;
    private javax.swing.JTextField cBankNo;
    private javax.swing.JLabel cFName;
    private javax.swing.JLabel cbBal;
    private javax.swing.JButton cbCancel;
    private javax.swing.JButton cbEnter;
    private javax.swing.JTextField dAccNo;
    private javax.swing.JLabel dCName;
    private javax.swing.JButton dClear;
    private javax.swing.JButton dClear1;
    private javax.swing.JTextField dDeposit;
    private javax.swing.JButton dDepositButton;
    private javax.swing.JButton dEnter;
    private javax.swing.JDesktopPane jDesktopPane3;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel93;
    private javax.swing.JLabel jLabel95;
    private javax.swing.JLabel jLabel96;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel36;
    private javax.swing.JPanel jPanel37;
    private javax.swing.JPanel jPanel38;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator6;
    private java.awt.Panel panel1;
    private javax.swing.JTextField wAccNo;
    private javax.swing.JButton wDepositButton;
    private javax.swing.JButton wEnterButton;
    private javax.swing.JTextField wWithdraw;
    // End of variables declaration//GEN-END:variables
}
